apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
status:
  loadBalancer: {}
---
# apiVersion: apps/v1
# datasources:
# - name: InfluxDB
#   type: influxdb
#   access: proxy
#   database: telegraf
#   isDefault: true
#   user: telegraf
#   password: pass
#   url: http://influxdb-service:8086
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - image: mygrafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: tarlo
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: kraken
        resources: {}
status: {}