apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb-service
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
type: Opaque
stringData:
  INFLUX_URL: http://influxdb-service:8086
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf  
  INFLUXDB_DB: gatling
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: kraken
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: kraken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - image: myinfluxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        envFrom:
            - secretRef:
                name: influxdb-secrets
        volumeMounts:
          - name: influx-persistent-storage
            mountPath: /var/lib/influxdb
          # - name: influxdb-config
          #   mountPath: /etc/influxdb/influxdb.conf
          #   subPath: influxdb.conf
          #   readOnly: true
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim:
          claimName: influx-pv-claim
      # - name: influxdb-config
      #   configMap:
      #     name: influxdb-config
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    app: influxdb
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"