apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb-service
spec:
  ports:
  - port: 8060
    protocol: TCP
    targetPort: 8060
  selector:
    app: influxdb
---
apiVersion: v1
kind: Secret
metadata:
    name: influx-secret
type: Opaque
data:
    admin: eWVldA==
    password: cGxlYXNl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb
        name: influxdb
        ports:
        - containerPort: 8060
        env:
        - name: INFLUXDB_DATABASE
          value: monitoring
        - name: INFLUXDB_USERNAME
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: influx-secret
          #     key: admin
        - name: INFLUXDB_PASSWORD
          value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: influx-secret
          #     key: password
        - name: INFLUXDB_HOST
          value: influxdb
        volumeMounts:
        - name: influx-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim:
          claimName: influx-pv-claim
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    app: influxdb
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"