apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: mynginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
    
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginx
    spec:
      containers:
      - image: mynginx
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
status: {}
