# apiVersion: v1
# kind: Service
# metadata:
#   name: mynginx
# spec:
#   selector:
#     app: mynginx
#   ports:
#     - port: 80
#       targetPort: 80
#   type: LoadBalancer
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginx
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginx
    spec:
      containers:
      - image: mynginx
        name: mynginx
        imagePullPolicy: Never
        resources: {}
status: {}
